### ISSUE TITLE
Correct PKGBUILD

### ISSUE THREAD

**Issue by loopset** [KaOS-Community-Packages/gtk-theme-arc-git#1]
I think that it will be better if you add this options to the PKGBUILD, like this:
```
./autogen.sh \
	  --prefix=/usr \
	  --disable-cinnamon \
	  --disable-gnome-shell \
	  --disable-metacity \
	  --disable-unity \
	  --disable-xfwm \
	  --disable-xfce-notify
```
With this options, you will disable all files not suported by KaOS (we not have cinnamon, for example)
:)

**Comment by FadeMind** [comment]
@loopset thanks. Done via https://github.com/KaOS-Community-Packages/gtk-theme-arc-git/commit/d2781a26fc11479aeaa60f04baa38f29994419d9
